* Video driver
** Noveau
*** Issue 1
    pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, device [8086:9d15]
    error status/mask=00000001/00002000
    [ 0] Receiver Error		(First)
*** Issue 2
    Suspend won't work.
*** Issue 3
    System won't reboot or shutdown after suspending.
*** Solution: Kernel parameters
    Summary:
    : GRUB_CMDLINE_LINUX_DEFAULT="pci=noaer nouveau.modeset=0"
**** pci=nomsi
     Solves issue 1, raises issue 2.
**** pci=noaer
     Solves issues 1 and 2.
**** nouveau.modeset=0
     Solves issue 3.
** Nvidia
*** Fonts
    Set DPI in KDE font settings to 96.
*** nvidia
**** Unsolved issues
     Suspend works only when not in a X session.
*** nvidia-lts
    Works out of the box.
* CPU fan sensor
  [[https://www.reddit.com/r/archlinux/comments/68m82j/no_sysclassthermalthermal_zone/][Possible solution (not attempted)]]
* Hibernation
  Hibernation requires a static swap file/partition.
  The swap device must be active. To activate it automatically at startup,
  add an entry to =/etc/fstab=.
** Kernel
   As of <2018-09-03 Mon>, hibernation only works with the lts kernel.
   #+begin_src bash
     pacman -S linux-lts
     pacman -R linux
     grub-mkconfig -o /boot/grub/grub.cfg
   #+end_src
** Initcpio
   Add ~resume~ to ~HOOKS=(...)~, *after the ~udev~ hook*.
   Regenerate the initcpio:
   #+begin_src bash
   mkinitcpio -p linux-lts
   #+end_src
** Grub
   Summary:
   : GRUB_CMDLINE_LINUX_DEFAULT="resume=<swap partition> resume_offset=<file offset>"
*** resume=<swap partition>
    Set the swap partition (or the partition where the swap file is located).
    E.g.: /dev/sda2
*** resume_offset=<file offset>
    Set the swap file offset in the partition.
    The swap file offset can be obtained with:
    : filefrag -v <swap file>
    The output is in a table format. The required value is located in the first row of the
    physical_offset column.
    For example:
    : # filefrag -v /swapfile
    : Filesystem type is: ef53
    : File size of /swapfile is 4294967296 (1048576 blocks of 4096 bytes)
    :  ext:     logical_offset:        physical_offset: length:   expected: flags:
    :    0:        0..       0:      38912..     38912:      1:            
    :    1:        1..   22527:      38913..     61439:  22527:             unwritten
    :    2:    22528..   53247:     899072..    929791:  30720:      61440: unwritten
    The value is the first 38912 with the two periods.
* TPM
  Disable fast boot in bios. Then blacklist the tpm kernel modules:
  =/etc/modprobe.d/blacklist.conf=
  #+begin_example
    blacklist tpm_crb
    blacklist tpm_tis
    blacklist tpm_tis_core
    blacklist tpm
    # blacklist rng_core
  #+end_example
* Power management
** TLP
   [[https://wiki.archlinux.org/index.php/TLP][TLP: Linux Advanced Power Management]]
*** Audio
    TLP disables audio hardware on idle by default. Toggling the audio card's power state
    can cause a popping sound or noticeable latency on some broken hardware.
    The popping sound can also be fixed by disabling [[TPM]].
    #+name: tlp-audio-patch
    #+begin_example
      --- tlp	2019-05-26 15:50:43.850600955 -0300
      +++ tlp	2019-05-26 15:53:25.714254941 -0300
      @@ -231,12 +231,12 @@
       # A value of 0 disables, >=1 enables power saving (recommended: 1).
       # Default: <none>
       SOUND_POWER_SAVE_ON_AC=0
      -SOUND_POWER_SAVE_ON_BAT=1
      +SOUND_POWER_SAVE_ON_BAT=0

       # Disable controller too (HDA only): Y/N.
       # Note: effective only when SOUND_POWER_SAVE_ON_AC/BAT is activated.
       # Default: Y
      -SOUND_POWER_SAVE_CONTROLLER=Y
      +SOUND_POWER_SAVE_CONTROLLER=N

       # Power off optical drive in UltraBay/MediaBay: 0=disable, 1=enable.
       # Drive can be powered on again by releasing (and reinserting) the eject lever
    #+end_example
    Tramp's =sudo= won't work with Babel's =stdin=.
    #+begin_src bash :dir /etc/default :stdin tlp-audio-patch :results verbatim
      tmpfile=$(mktemp) # create a temp file for the patch, since we'll need stdin for sudo.
      cat > "$tmpfile"  # dump contents
      echo n | sudo -p '' --stdin patch -i "$tmpfile"
    #+end_src
    #+results:
    : patching file tlp
